Add initial project files and GitHub workflows for release management

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,36 +3,97 @@
 name: Module release
 
 on:
-  workflow_dispatch:
-    inputs:
-      version:
-        description: 'Version to release'
-        type: string
-        required: true
-        default: '1.0.0'
   repository_dispatch:
     types: [remote_release_trigger]
 
+permissions:
+  contents: write
+
 jobs:
-  release:
-    runs-on: ubuntu-latest
-    outputs:
-      version: ${{ steps.set-version.outputs.version }}
-    steps:
-      - name: "set version"
-        id: set-version
-        run: |
-          if [ "${{ github.event_name }}" ==  "repository_dispatch" ] && [ "${{ github.event.client_payload.version }}" != "" ]; then
-            echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
-            echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
-          else
-            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
-            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
-          fi
-  info:
-    runs-on: ubuntu-latest
-    needs: release
-    steps:
-      - name: "Info"
-        run: |
-          echo "Version [out]: ${{ needs.release.outputs.version }}"
+  # check-tag:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Input parameters
+  #       run: |
+  #         echo "Version: ${{ github.event.client_payload.version }}" >> $GITHUB_STEP_SUMMARY
+
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+
+  #     - name: Check if tag exists
+  #       id: check_tag
+  #       uses: netcracker/qubership-workflow-hub/actions/tag-checker@main
+  #       with:
+  #         tag: 'v${{ github.event.client_payload.version }}'
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  #     - name: Output result
+  #       run: |
+  #         echo "Tag exists: ${{ steps.check_tag.outputs.exists }}"
+  #         echo "Tag name: v${{ github.event.client_payload.version }}"
+
+  #     - name: Fail if tag exists
+  #       if: steps.check_tag.outputs.exists == 'true'
+  #       run: |
+  #         echo "Tag already exists: v${{ github.event.client_payload.version }}" >> $GITHUB_STEP_SUMMARY
+  #         echo "Tag already exists: v${{ github.event.client_payload.version }}"
+  #         exit 1
+
+  # update-pom-version:
+  #   needs: [check-tag]
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     artifact_id: ${{ steps.config.outputs.artifact_id }}
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+
+  #     - name: Update pom.xml
+  #       id: config
+  #       uses: netcracker/qubership-workflow-hub/actions/pom-updater@main
+  #       with:
+  #         new_value: ${{ github.event.client_payload.version }}
+
+  #     - name: Commit Changes
+  #       uses: netcracker/qubership-workflow-hub/actions/commit-and-push@main
+  #       with:
+  #         commit_message: "Update pom.xml version to ${{ github.event.client_payload.version }}"
+
+  # tag:
+  #   needs: [update-pom-version]
+  #   uses: netcracker/qubership-workflow-hub/.github/workflows/tag-creator.yml@main
+  #   with:
+  #     tag-name: "v${{ github.event.client_payload.version }}"
+
+  github-release:
+    uses: netcracker/qubership-workflow-hub/.github/workflows/release-drafter.yml@main
+    with:
+      version: ${{ github.event.client_payload.version }}
+      publish: false
+
+# ==============================================================================
+  # release:
+  #   runs-on: ubuntu-latest
+  #   outputs:
+  #     version: ${{ steps.set-version.outputs.version }}
+  #   steps:
+  #     - name: "set version"
+  #       id: set-version
+  #       run: |
+  #         if [ "${{ github.event_name }}" ==  "repository_dispatch" ] && [ "${{ github.event.client_payload.version }}" != "" ]; then
+  #           echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_ENV
+  #           echo "version=${{ github.event.client_payload.version }}" >> $GITHUB_OUTPUT
+  #         else
+  #           echo "version=${{ github.event.inputs.version }}" >> $GITHUB_ENV
+  #           echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
+  #         fi
+  # info:
+  #   runs-on: ubuntu-latest
+  #   needs: release
+  #   steps:
+  #     - name: "Info"
+  #       run: |
+  #         echo "Version [out]: ${{ needs.release.outputs.version }}"
